spring:
  datasource:
    url: jdbc:postgresql://ec2-54-74-60-70.eu-west-1.compute.amazonaws.com:5432/d40l0libju1i1v
    username: lpxeklimrexmih
    password: fa518176c36803a3d82dab93654b28062282204bc6b82d860f2f44b191209fca
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port : 8081

data:
  predifined:
    financial:
      typ-scrtstn: 7
    counterparty-reference:
      rprtng-agn-cd: 304570552

security:
  whitelist-ips:
    - 78.61.234.239
    - 31.44.96.12
    - 84.15.148.130
    - 88.119.26.156
    - 35.228.68.66
    - 90.138.63.242
    - 127.0.0.1
