apiVersion: v1
kind: Service
metadata:
  name: nprdb-service
  labels:
    app: nprdb-service
spec:
  ports:
    - name: http
      port: 8081
  selector:
    app: nprdb-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nprdb-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nprdb-service
        version: v1
    spec:
      containers:
        - name: nprdb-service
          image: gcr.io/profitus-dev/nprdb-back-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver
            - name: SERVER_PORT
              value: '8081'
        # proxy_container
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=profitus-dev:europe-north1:profitus-test-db=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: cloudsql
              mountPath: /cloudsql
      # volumes
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
